### PR TITLE
Add On_Item_Expanding and On_Item_Expanded and associated stuff.

### PR DESCRIPTION
**Pull request by NicoPy**
Add On_Item_Expanding and On_Item_Expanded and associated stuff to Common_Controls

### CODE REVIEW

**Comment by zertovitch** [comment]
Great!

May I suggest a little change?
- move the definitions from "type NMTREEVIEW is..." to "function Message_To_NmTreeView_Ptr is..." to the private part of the spec (just before "end GWindows.Common_Controls;")
- rename NMTREEVIEW_Ptr as Pointer_To_NMTREEVIEW_Type (if GNAT Studio is in a good mood, the Refactoring context menu entry will do the job)
- rename Message_To_NmTreeView_Ptr as Message_To_NmTreeView_Pointer

The bonus there is that the corresponding lines in gwindows-common_controls-ex_tv.adb and gwindows-common_controls-ex_tv_generic.adb can be removed. Further, some stuff from those extensions could be moved to Common_Controls.

**Comment by zertovitch** [comment]
Possibly it is simpler (git-wise) if I accept the PR and make those small changes on master. Would it be better for you?

**Comment by NicoPy** [comment]
I'm working on it.

**Comment by NicoPy** [comment]
Done.

**Pull request merged**
